/* ============================================================
   RAWx CORE ASSET SPINE
   Single source of truth, shared by index.html (D2C) and
   index-b2b.html (Procurement Terminal).

   Plain classic script — NOT an ES module. Top-level const/
   function declarations here are visible to any <script> that
   loads after this one on the same page (shared global lexical
   scope), so both portals just do:

       <script src="core-assets.js"></script>

   ...before their own inline <script>. No bundler, no CORS
   issues on file://, no build step.
============================================================ */

/* ============================================================
   CATEGORY META — label + sort weight (by frequency)
============================================================ */
const SECTIONS = [
  { key:'scrap',      label:'Scrap' },
  { key:'pin',         label:'Pinboard' },
  { key:'activewear',  label:'Activewear' },
  { key:'thong',       label:'Thong' },
  { key:'twoset',      label:'2-Piece Set' },
  { key:'panty',       label:'Panty' },
  { key:'lingerie',    label:'Lingerie' },
  { key:'bodysuit',    label:'Bodysuit' },
  { key:'ig',          label:'Instagram' },
  { key:'essential',   label:'Essential' },
  { key:'image',       label:'Image' },
  { key:'images',      label:'Images' },
  { key:'misc',        label:'Misc' }
];

/* ============================================================
   ASSET REGISTRY — generated 1:1 from filelist.txt (462 files)
   Format: [title, categoryKey, exactFilename]
============================================================ */
const BASE = 'https://media.githubusercontent.com/media/handfilm/rawx-lingerie/main/assets/images/';
const RAW = [
['2-Piece Set 1','twoset','2set (1).jpg'],
['2-Piece Set 1','twoset','2set (1).webp'],
['2-Piece Set 10','twoset','2set (10).webp'],
['2-Piece Set 11','twoset','2set (11).webp'],
['2-Piece Set 12','twoset','2set (12).webp'],
['2-Piece Set 13','twoset','2set (13).webp'],
['2-Piece Set 14','twoset','2set (14).webp'],
['2-Piece Set 15','twoset','2set (15).webp'],
['2-Piece Set 16','twoset','2set (16).webp'],
['2-Piece Set 17','twoset','2set (17).webp'],
['2-Piece Set 18','twoset','2set (18).webp'],
['2-Piece Set 19','twoset','2set (19).webp'],
['2-Piece Set 2','twoset','2set (2).jpg'],
['2-Piece Set 2','twoset','2set (2).webp'],
['2-Piece Set 20','twoset','2set (20).webp'],
['2-Piece Set 21','twoset','2set (21).webp'],
['2-Piece Set 22','twoset','2set (22).webp'],
['2-Piece Set 23','twoset','2set (23).webp'],
['2-Piece Set 24','twoset','2set (24).webp'],
['2-Piece Set 25','twoset','2set (25).webp'],
['2-Piece Set 26','twoset','2set (26).webp'],
['2-Piece Set 27','twoset','2set (27).webp'],
['2-Piece Set 28','twoset','2set (28).webp'],
['2-Piece Set 29','twoset','2set (29).webp'],
['2-Piece Set 3','twoset','2set (3).jpg'],
['2-Piece Set 3','twoset','2set (3).webp'],
['2-Piece Set 30','twoset','2set (30).webp'],
['2-Piece Set 31','twoset','2set (31).webp'],
['2-Piece Set 32','twoset','2set (32).webp'],
['2-Piece Set 33','twoset','2set (33).webp'],
['2-Piece Set 4','twoset','2set (4).jpg'],
['2-Piece Set 4','twoset','2set (4).webp'],
['2-Piece Set 5','twoset','2set (5).jpg'],
['2-Piece Set 5','twoset','2set (5).webp'],
['2-Piece Set 6','twoset','2set (6).jpg'],
['2-Piece Set 6','twoset','2set (6).webp'],
['2-Piece Set 7','twoset','2set (7).webp'],
['2-Piece Set 8','twoset','2set (8).webp'],
['2-Piece Set 9','twoset','2set (9).webp'],
['2-Piece Set','twoset','2set.jpg'],
['2-Piece Set','twoset','2set.webp'],
['Frame 56915','misc','56915.webp'],
['Activewear 1','activewear','activewear (1).webp'],
['Activewear 10','activewear','activewear (10).webp'],
['Activewear 11','activewear','activewear (11).webp'],
['Activewear 12','activewear','activewear (12).webp'],
['Activewear 13','activewear','activewear (13).webp'],
['Activewear 14','activewear','activewear (14).webp'],
['Activewear 15','activewear','activewear (15).webp'],
['Activewear 16','activewear','activewear (16).webp'],
['Activewear 17','activewear','activewear (17).webp'],
['Activewear 18','activewear','activewear (18).webp'],
['Activewear 19','activewear','activewear (19).webp'],
['Activewear 2','activewear','activewear (2).webp'],
['Activewear 20','activewear','activewear (20).webp'],
['Activewear 21','activewear','activewear (21).webp'],
['Activewear 22','activewear','activewear (22).webp'],
['Activewear 23','activewear','activewear (23).webp'],
['Activewear 24','activewear','activewear (24).webp'],
['Activewear 25','activewear','activewear (25).webp'],
['Activewear 26','activewear','activewear (26).webp'],
['Activewear 27','activewear','activewear (27).webp'],
['Activewear 28','activewear','activewear (28).webp'],
['Activewear 29','activewear','activewear (29).webp'],
['Activewear 3','activewear','activewear (3).webp'],
['Activewear 30','activewear','activewear (30).webp'],
['Activewear 31','activewear','activewear (31).webp'],
['Activewear 32','activewear','activewear (32).webp'],
['Activewear 33','activewear','activewear (33).webp'],
['Activewear 34','activewear','activewear (34).webp'],
['Activewear 35','activewear','activewear (35).webp'],
['Activewear 36','activewear','activewear (36).webp'],
['Activewear 37','activewear','activewear (37).webp'],
['Activewear 38','activewear','activewear (38).webp'],
['Activewear 39','activewear','activewear (39).webp'],
['Activewear 4','activewear','activewear (4).webp'],
['Activewear 40','activewear','activewear (40).webp'],
['Activewear 41','activewear','activewear (41).webp'],
['Activewear 42','activewear','activewear (42).webp'],
['Activewear 43','activewear','activewear (43).webp'],
['Activewear 44','activewear','activewear (44).webp'],
['Activewear 45','activewear','activewear (45).webp'],
['Activewear 46','activewear','activewear (46).webp'],
['Activewear 47','activewear','activewear (47).webp'],
['Activewear 48','activewear','activewear (48).webp'],
['Activewear 49','activewear','activewear (49).webp'],
['Activewear 5','activewear','activewear (5).webp'],
['Activewear 50','activewear','activewear (50).webp'],
['Activewear 51','activewear','activewear (51).webp'],
['Activewear 52','activewear','activewear (52).webp'],
['Activewear 53','activewear','activewear (53).webp'],
['Activewear 54','activewear','activewear (54).webp'],
['Activewear 55','activewear','activewear (55).webp'],
['Activewear 56','activewear','activewear (56).webp'],
['Activewear 57','activewear','activewear (57).webp'],
['Activewear 58','activewear','activewear (58).webp'],
['Activewear 59','activewear','activewear (59).webp'],
['Activewear 6','activewear','activewear (6).webp'],
['Activewear 7','activewear','activewear (7).webp'],
['Activewear 8','activewear','activewear (8).webp'],
['Activewear 9','activewear','activewear (9).webp'],
['Bodysuit 1','bodysuit','bodysuit (1).webp'],
['Bodysuit 11','bodysuit','bodysuit (11).jpeg'],
['Bodysuit 12','bodysuit','bodysuit (12).jpeg'],
['Bodysuit 13','bodysuit','bodysuit (13).jpeg'],
['Bodysuit 14','bodysuit','bodysuit (14).jpeg'],
['Bodysuit 14','bodysuit','bodysuit (14).png'],
['Bodysuit 15','bodysuit','bodysuit (15).jpeg'],
['Bodysuit 15','bodysuit','bodysuit (15).png'],
['Bodysuit 16','bodysuit','bodysuit (16).jpeg'],
['Bodysuit 16','bodysuit','bodysuit (16).webp'],
['Bodysuit 17','bodysuit','bodysuit (17).jpeg'],
['Bodysuit 17','bodysuit','bodysuit (17).webp'],
['Bodysuit 18','bodysuit','bodysuit (18).jpeg'],
['Bodysuit 18','bodysuit','bodysuit (18).webp'],
['Bodysuit 19','bodysuit','bodysuit (19).webp'],
['Bodysuit 2','bodysuit','bodysuit (2).webp'],
['Bodysuit 20','bodysuit','bodysuit (20).webp'],
['Bodysuit 3','bodysuit','bodysuit (3).webp'],
['Bodysuit 4','bodysuit','bodysuit (4).webp'],
['Bodysuit 5','bodysuit','bodysuit (5).webp'],
['Bodysuit 6','bodysuit','bodysuit (6).webp'],
['Bodysuit 61','bodysuit','bodysuit (61).jpg'],
['Bodysuit 7','bodysuit','bodysuit (7).webp'],
['Bodysuit 8','bodysuit','bodysuit (8).webp'],
['Bodysuit 9','bodysuit','bodysuit (9).webp'],
['Bodysuit','bodysuit','bodysuit.jpg'],
['Bodysuit','bodysuit','bodysuit.webp'],
['Essential 1','essential','essential (1).webp'],
['Essential 2','essential','essential (2).webp'],
['Essential 3','essential','essential (3).webp'],
['Essential 4','essential','essential (4).webp'],
['Essential 5','essential','essential (5).webp'],
['Essential 6','essential','essential (6).webp'],
['Essential 7','essential','essential (7).webp'],
['Essential 8','essential','essential (8).webp'],
['Essential 9','essential','essential (9).webp'],
['Instagram 1','ig','ig (1).png'],
['Instagram 1','ig','ig (1).webp'],
['Instagram 10','ig','ig (10).webp'],
['Instagram 11','ig','ig (11).webp'],
['Instagram 12','ig','ig (12).webp'],
['Instagram 13','ig','ig (13).webp'],
['Instagram 2','ig','ig (2).jpg'],
['Instagram 2','ig','ig (2).webp'],
['Instagram 3','ig','ig (3).webp'],
['Instagram 4','ig','ig (4).webp'],
['Instagram 5','ig','ig (5).webp'],
['Instagram 6','ig','ig (6).webp'],
['Instagram 7','ig','ig (7).webp'],
['Instagram 8','ig','ig (8).webp'],
['Instagram 9','ig','ig (9).webp'],
['Image 13','image','image (13).jpg'],
['Image 14','image','image (14).jpg'],
['Image 15','image','image (15).jpg'],
['Image 16','image','image (16).jpg'],
['Image 17','image','image (17).jpg'],
['Image 18','image','image (18).jpg'],
['Image 19','image','image (19).jpg'],
['Image 20','image','image (20).jpg'],
['Images 19','images','images (19).jpeg'],
['Images 20','images','images (20).jpeg'],
['Images 21','images','images (21).jpeg'],
['Images 22','images','images (22).jpeg'],
['Images 23','images','images (23).jpeg'],
['Images 24','images','images (24).jpeg'],
['Images 25','images','images (25).jpeg'],
['Lingerie 1','lingerie','Lingerie (1).webp'],
['Lingerie 10','lingerie','Lingerie (10).webp'],
['Lingerie 11','lingerie','Lingerie (11).webp'],
['Lingerie 12','lingerie','Lingerie (12).webp'],
['Lingerie 13','lingerie','Lingerie (13).webp'],
['Lingerie 14','lingerie','Lingerie (14).webp'],
['Lingerie 15','lingerie','Lingerie (15).webp'],
['Lingerie 16','lingerie','Lingerie (16).webp'],
['Lingerie 17','lingerie','Lingerie (17).webp'],
['Lingerie 18','lingerie','Lingerie (18).webp'],
['Lingerie 19','lingerie','Lingerie (19).webp'],
['Lingerie 2','lingerie','Lingerie (2).webp'],
['Lingerie 20','lingerie','Lingerie (20).webp'],
['Lingerie 21','lingerie','Lingerie (21).webp'],
['Lingerie 22','lingerie','Lingerie (22).webp'],
['Lingerie 23','lingerie','Lingerie (23).webp'],
['Lingerie 24','lingerie','Lingerie (24).webp'],
['Lingerie 25','lingerie','Lingerie (25).webp'],
['Lingerie 26','lingerie','Lingerie (26).webp'],
['Lingerie 27','lingerie','Lingerie (27).webp'],
['Lingerie 28','lingerie','Lingerie (28).webp'],
['Lingerie 29','lingerie','Lingerie (29).webp'],
['Lingerie 3','lingerie','Lingerie (3).webp'],
['Lingerie 30','lingerie','Lingerie (30).webp'],
['Lingerie 31','lingerie','Lingerie (31).webp'],
['Lingerie 32','lingerie','Lingerie (32).webp'],
['Lingerie 33','lingerie','Lingerie (33).webp'],
['Lingerie 34','lingerie','Lingerie (34).webp'],
['Lingerie 4','lingerie','Lingerie (4).webp'],
['Lingerie 5','lingerie','Lingerie (5).webp'],
['Lingerie 6','lingerie','Lingerie (6).webp'],
['Lingerie 7','lingerie','Lingerie (7).webp'],
['Lingerie 8','lingerie','Lingerie (8).webp'],
['Lingerie 9','lingerie','Lingerie (9).webp'],
['Panty 1','panty','panty (1).webp'],
['Panty 10','panty','panty (10).webp'],
['Panty 11','panty','panty (11).webp'],
['Panty 12','panty','panty (12).webp'],
['Panty 13','panty','panty (13).webp'],
['Panty 14','panty','panty (14).webp'],
['Panty 15','panty','panty (15).webp'],
['Panty 16','panty','panty (16).webp'],
['Panty 17','panty','panty (17).webp'],
['Panty 18','panty','panty (18).webp'],
['Panty 19','panty','panty (19).webp'],
['Panty 2','panty','panty (2).webp'],
['Panty 20','panty','panty (20).webp'],
['Panty 21','panty','panty (21).webp'],
['Panty 22','panty','panty (22).webp'],
['Panty 23','panty','panty (23).webp'],
['Panty 24','panty','panty (24).webp'],
['Panty 25','panty','panty (25).webp'],
['Panty 26','panty','panty (26).webp'],
['Panty 27','panty','panty (27).webp'],
['Panty 28','panty','panty (28).webp'],
['Panty 29','panty','panty (29).webp'],
['Panty 3','panty','panty (3).webp'],
['Panty 30','panty','panty (30).webp'],
['Panty 31','panty','panty (31).webp'],
['Panty 32','panty','panty (32).webp'],
['Panty 33','panty','panty (33).webp'],
['Panty 34','panty','panty (34).webp'],
['Panty 35','panty','panty (35).webp'],
['Panty 4','panty','panty (4).webp'],
['Panty 5','panty','panty (5).webp'],
['Panty 6','panty','panty (6).webp'],
['Panty 7','panty','panty (7).webp'],
['Panty 8','panty','panty (8).webp'],
['Panty 9','panty','panty (9).webp'],
['Pinboard 1','pin','pin (1).jpg'],
['Pinboard 10','pin','pin (10).jpg'],
['Pinboard 11','pin','pin (11).jpg'],
['Pinboard 12','pin','pin (12).jpg'],
['Pinboard 13','pin','pin (13).jpg'],
['Pinboard 14','pin','pin (14).jpg'],
['Pinboard 15','pin','pin (15).jpg'],
['Pinboard 16','pin','pin (16).jpg'],
['Pinboard 17','pin','pin (17).jpg'],
['Pinboard 18','pin','pin (18).jpg'],
['Pinboard 19','pin','pin (19).jpg'],
['Pinboard 2','pin','pin (2).jpg'],
['Pinboard 20','pin','pin (20).jpg'],
['Pinboard 21','pin','pin (21).jpg'],
['Pinboard 22','pin','pin (22).jpg'],
['Pinboard 23','pin','pin (23).jpg'],
['Pinboard 24','pin','pin (24).jpg'],
['Pinboard 25','pin','pin (25).jpg'],
['Pinboard 26','pin','pin (26).jpg'],
['Pinboard 27','pin','pin (27).jpg'],
['Pinboard 28','pin','pin (28).jpg'],
['Pinboard 29','pin','pin (29).jpg'],
['Pinboard 30','pin','pin (30).jpg'],
['Pinboard 31','pin','pin (31).jpg'],
['Pinboard 32','pin','pin (32).jpg'],
['Pinboard 33','pin','pin (33).jpg'],
['Pinboard 34','pin','pin (34).jpg'],
['Pinboard 36','pin','pin (36).jpg'],
['Pinboard 37','pin','pin (37).jpg'],
['Pinboard 38','pin','pin (38).jpg'],
['Pinboard 39','pin','pin (39).jpg'],
['Pinboard 4','pin','pin (4).jpg'],
['Pinboard 40','pin','pin (40).jpg'],
['Pinboard 41','pin','pin (41).jpg'],
['Pinboard 42','pin','pin (42).jpg'],
['Pinboard 43','pin','pin (43).jpg'],
['Pinboard 45','pin','pin (45).jpg'],
['Pinboard 46','pin','pin (46).jpg'],
['Pinboard 47','pin','pin (47).jpg'],
['Pinboard 48','pin','pin (48).jpg'],
['Pinboard 49','pin','pin (49).jpg'],
['Pinboard 5','pin','pin (5).jpg'],
['Pinboard 50','pin','pin (50).jpg'],
['Pinboard 51','pin','pin (51).jpg'],
['Pinboard 52','pin','pin (52).jpg'],
['Pinboard 54','pin','pin (54).jpg'],
['Pinboard 55','pin','pin (55).jpg'],
['Pinboard 56','pin','pin (56).jpg'],
['Pinboard 57','pin','pin (57).jpg'],
['Pinboard 58','pin','pin (58).jpg'],
['Pinboard 59','pin','pin (59).jpg'],
['Pinboard 6','pin','pin (6).jpg'],
['Pinboard 60','pin','pin (60).jpg'],
['Pinboard 61','pin','pin (61).jpg'],
['Pinboard 62','pin','pin (62).jpg'],
['Pinboard 63','pin','pin (63).jpg'],
['Pinboard 64','pin','pin (64).jpg'],
['Pinboard 65','pin','pin (65).jpg'],
['Pinboard 66','pin','pin (66).jpg'],
['Pinboard 67','pin','pin (67).jpg'],
['Pinboard 68','pin','pin (68).jpg'],
['Pinboard 69','pin','pin (69).jpg'],
['Pinboard 7','pin','pin (7).jpg'],
['Pinboard 8','pin','pin (8).jpg'],
['Pinboard 9','pin','pin (9).jpg'],
['Scrap 1','scrap','scrap (1).jpeg'],
['Scrap 1','scrap','scrap (1).jpg'],
['Scrap 1','scrap','scrap (1).png'],
['Scrap 1','scrap','scrap (1).webp'],
['Scrap 10','scrap','scrap (10).jpg'],
['Scrap 10','scrap','scrap (10).png'],
['Scrap 11','scrap','scrap (11).jpg'],
['Scrap 12','scrap','scrap (12).jpg'],
['Scrap 13','scrap','scrap (13).jpg'],
['Scrap 14','scrap','scrap (14).jpg'],
['Scrap 15','scrap','scrap (15).jpg'],
['Scrap 16','scrap','scrap (16).jpg'],
['Scrap 17','scrap','scrap (17).jpg'],
['Scrap 18','scrap','scrap (18).jpg'],
['Scrap 19','scrap','scrap (19).jpg'],
['Scrap 2','scrap','scrap (2).jpg'],
['Scrap 2','scrap','scrap (2).png'],
['Scrap 20','scrap','scrap (20).jpg'],
['Scrap 21','scrap','scrap (21).jpg'],
['Scrap 22','scrap','scrap (22).jpg'],
['Scrap 23','scrap','scrap (23).jpg'],
['Scrap 24','scrap','scrap (24).jpg'],
['Scrap 25','scrap','scrap (25).jpg'],
['Scrap 26','scrap','scrap (26).jpg'],
['Scrap 27','scrap','scrap (27).jpg'],
['Scrap 28','scrap','scrap (28).jpg'],
['Scrap 29','scrap','scrap (29).jpg'],
['Scrap 3','scrap','scrap (3).jpg'],
['Scrap 3','scrap','scrap (3).png'],
['Scrap 30','scrap','scrap (30).jpg'],
['Scrap 31','scrap','scrap (31).jpg'],
['Scrap 32','scrap','scrap (32).jpg'],
['Scrap 33','scrap','scrap (33).jpg'],
['Scrap 34','scrap','scrap (34).jpg'],
['Scrap 35','scrap','scrap (35).jpg'],
['Scrap 36','scrap','scrap (36).jpg'],
['Scrap 37','scrap','scrap (37).jpg'],
['Scrap 38','scrap','scrap (38).jpg'],
['Scrap 39','scrap','scrap (39).jpg'],
['Scrap 4','scrap','scrap (4).jpg'],
['Scrap 4','scrap','scrap (4).png'],
['Scrap 40','scrap','scrap (40).jpg'],
['Scrap 41','scrap','scrap (41).jpg'],
['Scrap 42','scrap','scrap (42).jpg'],
['Scrap 43','scrap','scrap (43).jpg'],
['Scrap 44','scrap','scrap (44).jpg'],
['Scrap 45','scrap','scrap (45).jpg'],
['Scrap 46','scrap','scrap (46).jpg'],
['Scrap 47','scrap','scrap (47).jpg'],
['Scrap 48','scrap','scrap (48).jpg'],
['Scrap 49','scrap','scrap (49).jpg'],
['Scrap 5','scrap','scrap (5).jpg'],
['Scrap 5','scrap','scrap (5).png'],
['Scrap 50','scrap','scrap (50).jpg'],
['Scrap 51','scrap','scrap (51).jpg'],
['Scrap 52','scrap','scrap (52).jpg'],
['Scrap 53','scrap','scrap (53).jpg'],
['Scrap 54','scrap','scrap (54).jpg'],
['Scrap 55','scrap','scrap (55).jpg'],
['Scrap 56','scrap','scrap (56).jpg'],
['Scrap 57','scrap','scrap (57).jpg'],
['Scrap 58','scrap','scrap (58).jpg'],
['Scrap 59','scrap','scrap (59).jpg'],
['Scrap 6','scrap','scrap (6).jpg'],
['Scrap 6','scrap','scrap (6).png'],
['Scrap 60','scrap','scrap (60).jpg'],
['Scrap 61','scrap','scrap (61).jpg'],
['Scrap 62','scrap','scrap (62).jpg'],
['Scrap 63','scrap','scrap (63).jpg'],
['Scrap 64','scrap','scrap (64).jpg'],
['Scrap 65','scrap','scrap (65).jpg'],
['Scrap 66','scrap','scrap (66).jpg'],
['Scrap 67','scrap','scrap (67).jpg'],
['Scrap 68','scrap','scrap (68).jpg'],
['Scrap 69','scrap','scrap (69).jpg'],
['Scrap 7','scrap','scrap (7).jpg'],
['Scrap 7','scrap','scrap (7).png'],
['Scrap 70','scrap','scrap (70).jpg'],
['Scrap 71','scrap','scrap (71).jpg'],
['Scrap 72','scrap','scrap (72).jpg'],
['Scrap 73','scrap','scrap (73).jpg'],
['Scrap 74','scrap','scrap (74).jpg'],
['Scrap 75','scrap','scrap (75).jpg'],
['Scrap 76','scrap','scrap (76).jpg'],
['Scrap 77','scrap','scrap (77).jpg'],
['Scrap 78','scrap','scrap (78).jpg'],
['Scrap 79','scrap','scrap (79).jpg'],
['Scrap 8','scrap','scrap (8).jpg'],
['Scrap 8','scrap','scrap (8).png'],
['Scrap 80','scrap','scrap (80).jpg'],
['Scrap 81','scrap','scrap (81).jpg'],
['Scrap 82','scrap','scrap (82).jpg'],
['Scrap 83','scrap','scrap (83).jpg'],
['Scrap 84','scrap','scrap (84).jpg'],
['Scrap 85','scrap','scrap (85).jpg'],
['Scrap 86','scrap','scrap (86).jpg'],
['Scrap 87','scrap','scrap (87).jpg'],
['Scrap 88','scrap','scrap (88).jpg'],
['Scrap 89','scrap','scrap (89).jpg'],
['Scrap 9','scrap','scrap (9).jpg'],
['Scrap 9','scrap','scrap (9).png'],
['Scrap 90','scrap','scrap (90).jpg'],
['Scrap 91','scrap','scrap (91).jpg'],
['Thong 1','thong','thong (1).jpg'],
['Thong 1','thong','thong (1).png'],
['Thong 1','thong','thong (1).webp'],
['Thong 10','thong','thong (10).webp'],
['Thong 11','thong','thong (11).webp'],
['Thong 12','thong','thong (12).webp'],
['Thong 13','thong','thong (13).webp'],
['Thong 14','thong','thong (14).webp'],
['Thong 15','thong','thong (15).webp'],
['Thong 16','thong','thong (16).webp'],
['Thong 17','thong','thong (17).webp'],
['Thong 18','thong','thong (18).webp'],
['Thong 19','thong','thong (19).webp'],
['Thong 2','thong','thong (2).png'],
['Thong 2','thong','thong (2).webp'],
['Thong 20','thong','thong (20).webp'],
['Thong 21','thong','thong (21).webp'],
['Thong 22','thong','thong (22).webp'],
['Thong 23','thong','thong (23).webp'],
['Thong 24','thong','thong (24).webp'],
['Thong 25','thong','thong (25).webp'],
['Thong 26','thong','thong (26).webp'],
['Thong 27','thong','thong (27).webp'],
['Thong 28','thong','thong (28).webp'],
['Thong 29','thong','thong (29).webp'],
['Thong 3','thong','thong (3).webp'],
['Thong 30','thong','thong (30).webp'],
['Thong 31','thong','thong (31).webp'],
['Thong 32','thong','thong (32).webp'],
['Thong 33','thong','thong (33).webp'],
['Thong 34','thong','thong (34).webp'],
['Thong 35','thong','thong (35).webp'],
['Thong 36','thong','thong (36).webp'],
['Thong 37','thong','thong (37).webp'],
['Thong 38','thong','thong (38).webp'],
['Thong 39','thong','thong (39).webp'],
['Thong 4','thong','thong (4).webp'],
['Thong 40','thong','thong (40).webp'],
['Thong 41','thong','thong (41).webp'],
['Thong 42','thong','thong (42).webp'],
['Thong 43','thong','thong (43).webp'],
['Thong 44','thong','thong (44).webp'],
['Thong 45','thong','thong (45).webp'],
['Thong 46','thong','thong (46).webp'],
['Thong 47','thong','thong (47).webp'],
['Thong 48','thong','thong (48).webp'],
['Thong 49','thong','thong (49).webp'],
['Thong 5','thong','thong (5).webp'],
['Thong 50','thong','thong (50).webp'],
['Thong 51','thong','thong (51).webp'],
['Thong 52','thong','thong (52).webp'],
['Thong 53','thong','thong (53).webp'],
['Thong 6','thong','thong (6).webp'],
['Thong 7','thong','thong (7).webp'],
['Thong 8','thong','thong (8).webp'],
['Thong 9','thong','thong (9).webp'],
['Thong','thong','thong.png'],
['Thong','thong','thong.webp']
];

function isVideoExt(fn){ return /\.(mp4|webm|mov)$/i.test(fn); }

/* Precomputed once — every consumer (D2C + B2B) reads from this. */
const PHOTOS = RAW.map((r, i) => ({
  id: i,
  title: r[0],
  kind: r[1],
  file: r[2],
  src: BASE + encodeURIComponent(r[2]),
  video: isVideoExt(r[2])
}));

/* Grouped index for fast category pulls — this is what the D2C
   site leans on to populate the Hero, Category Strip, The Edit,
   and Bestsellers straight from real production frames. */
const PHOTOS_BY_KIND = PHOTOS.reduce((acc, p) => {
  (acc[p.kind] = acc[p.kind] || []).push(p);
  return acc;
}, {});

/* Random, non-repeating pull of `count` still frames from a
   category. Used by both portals wherever a "randomized" or
   "most relevant" image set is needed. */
function pickFromKind(kind, count, opts){
  opts = opts || {};
  const pool = (PHOTOS_BY_KIND[kind] || []).filter(p => opts.allowVideo ? true : !p.video);
  if (!pool.length) return [];
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

/* ============================================================
   B2B GARMENT SPECS — technical naming, materials, MOQ, sizing
   Applied only to true garment categories; reference/moodboard
   categories (pin, scrap, ig, image, images, misc) stay as
   plain archive frames, matching the "asset engine" behavior.
============================================================ */
const GARMENT_SPECS = {
  twoset:     { code:'2PC', label:'2-Piece Tech Set',            material:'78% Nylon / 22% Elastane — bonded seam construction',        moq:300,  sizes:['XS','S','M','L','XL'] },
  activewear: { code:'ACT', label:'Compression Activewear',      material:'88% Polyester / 12% Spandex — 4-way stretch, moisture-wick', moq:500,  sizes:['XS','S','M','L','XL','XXL'] },
  thong:      { code:'THG', label:'Micro-Mesh Thong',            material:'85% Microfiber Mesh / 15% Elastane — laser-cut edge',        moq:1000, sizes:['XS','S','M','L'] },
  panty:      { code:'PTY', label:'Flat-Seam Panty',             material:'80% Cotton / 20% Elastane — flat-lock stitching',            moq:1000, sizes:['XS','S','M','L','XL'] },
  lingerie:   { code:'LGN', label:'Tech-Lace Lingerie Set',      material:'70% Tech-Lace / 30% Elastane — underwire-compatible',        moq:250,  sizes:['S','M','L'] },
  bodysuit:   { code:'BDS', label:'Seamless Tech-Mesh Bodysuit', material:'82% Nylon / 18% Spandex — 4-way compression stretch',        moq:300,  sizes:['XS','S','M','L','XL'] },
  essential:  { code:'ESN', label:'Modal Base Essential',        material:'95% Modal / 5% Elastane — second-skin base layer',           moq:500,  sizes:['XS','S','M','L','XL'] }
};

const DESC_FRAGMENTS = [
  'Engineered for a compressive, second-skin fit with raw-edge trims for a stripped-back technical profile.',
  'Built on a bonded seam architecture — no visible stitching, minimal chafe, consistent structure at scale.',
  'Cut for a high-retention silhouette with reinforced stress points at load-bearing seams.',
  'Finished with a matte-technical hand-feel; engineered to hold shape through repeated wash cycles.',
  'Laser-cut panel construction eliminates bulk seams for a low-profile fit under outerwear.'
];

function isGarment(p){ return !!GARMENT_SPECS[p.kind]; }

/* ============================================================
   PRODUCT OVERRIDES — per-SKU data source
   Key = exact filename (3rd value in each RAW row, e.g. "bodysuit (1).webp").
   Fill in real specs here as they're finalized; any field you omit
   falls back to the category default in GARMENT_SPECS above.
   All fields are optional except when you want to override them.
============================================================
   Example:
   "bodysuit (1).webp": {
     code:     "RX-BDS-001",                                  // overrides generated code
     name:     "RX-BDS-001: Seamless Tech-Mesh Bodysuit — Onyx",
     desc:     "Underbust seam-free construction, matte-finish...",
     material: "82% Nylon / 18% Spandex — bonded seam, 4-way stretch",
     moq:      300,
     sizes:    "XS / S / M / L / XL",
     price:    "$14.50 / unit FOB Dhaka",                      // optional, shown if present
     colorways:"Onyx / Blush / Graphite"                       // optional, shown if present
   }
============================================================ */
const PRODUCT_OVERRIDES = {
  // "bodysuit (1).webp": { code:"RX-BDS-001", moq:300, price:"$14.50 / unit FOB" },
};

function buildProductData(p){
  const spec = GARMENT_SPECS[p.kind];
  if (!spec) return null;

  const idNum = String(p.id % 999 + 1).padStart(3,'0');
  const generatedCode = `RX-${spec.code}-${idNum}`;
  const desc = DESC_FRAGMENTS[p.id % DESC_FRAGMENTS.length];
  const moqVariance = (p.id % 3) * 50;

  const base = {
    code: generatedCode,
    name: `${generatedCode}: ${spec.label}`,
    desc,
    material: spec.material,
    moq: spec.moq + moqVariance,
    sizes: spec.sizes.join(' / '),
    price: null,
    colorways: null
  };

  const override = PRODUCT_OVERRIDES[p.file];
  return override ? { ...base, ...override } : base;
}
